export type Category =
  | "Values and Principles"
  | "What is the UK?"
  | "British History"
  | "Modern, Thriving Society"
  | "Government, Law and Your Role";

export interface PoolQuestion {
  id: string;
  category: Category;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

/**
 * Original practice questions written to cover the topic areas of the
 * official "Life in the UK" handbook. Not copied from any commercial
 * question bank. Recombined per-test by lib/tests.ts.
 */
export const questionPool: PoolQuestion[] = [
  // ---- Values and Principles ----
  {
    id: "vp-1",
    category: "Values and Principles",
    question: "Which of these is one of the fundamental principles of British life listed in the Life in the UK handbook?",
    options: ["Tolerance of those with different faiths and beliefs", "Mandatory military service", "A single official state religion for all citizens", "Compulsory voting in all elections"],
    correctIndex: 0,
    explanation: "The handbook lists democracy, the rule of law, individual liberty, and tolerance of different faiths and beliefs as fundamental principles.",
  },
  {
    id: "vp-2",
    category: "Values and Principles",
    question: "What is expected of permanent residents and citizens of the UK regarding the law?",
    options: ["To obey and respect the law", "To only follow laws they personally agree with", "To report to a local council monthly", "To join a political party"],
    correctIndex: 0,
    explanation: "All residents are expected to obey the law and to respect the rights of other people to live their lives in their own way.",
  },
  {
    id: "vp-3",
    category: "Values and Principles",
    question: "Which document is often referred to as a cornerstone of British civil liberties, signed in 1215?",
    options: ["Magna Carta", "The Bill of Rights", "The Domesday Book", "The Act of Union"],
    correctIndex: 0,
    explanation: "Magna Carta, signed by King John in 1215, established the principle that everyone, including the king, is subject to the law.",
  },
  {
    id: "vp-4",
    category: "Values and Principles",
    question: "Freedom of speech in the UK is:",
    options: ["A right, balanced against laws on hate speech and public order", "Completely unlimited with no legal restrictions", "Only granted to British-born citizens", "Restricted to approved topics"],
    correctIndex: 0,
    explanation: "Freedom of speech is a long-standing tradition, but it is balanced by laws that prevent hate speech and incitement to violence.",
  },
  {
    id: "vp-5",
    category: "Values and Principles",
    question: "Participation in community life in the UK is:",
    options: ["Encouraged, for example through volunteering", "Legally compulsory for all adults", "Discouraged for new residents", "Only open to British citizens"],
    correctIndex: 0,
    explanation: "Participating in community activities, such as volunteering, is encouraged as part of integrating into British life.",
  },
  {
    id: "vp-6",
    category: "Values and Principles",
    question: "The rule of law means that:",
    options: ["Everyone, including those in government, must obey the law", "Only ordinary citizens must obey the law", "Laws can be ignored if inconvenient", "The monarch is above the law"],
    correctIndex: 0,
    explanation: "The rule of law is a core British value: no one, including the government, is above the law.",
  },
  {
    id: "vp-7",
    category: "Values and Principles",
    question: "Which of the following best describes 'individual liberty' as a British value?",
    options: ["The right to live your life as you choose, within the law", "The right to ignore laws you dislike", "The obligation to conform to a single lifestyle", "A right granted only after 10 years of residence"],
    correctIndex: 0,
    explanation: "Individual liberty means people are free to live their lives as they choose, provided they act within the law.",
  },

  // ---- What is the UK? ----
  {
    id: "uk-1",
    category: "What is the UK?",
    question: "Which four countries make up the United Kingdom?",
    options: ["England, Scotland, Wales and Northern Ireland", "England, Ireland, Scotland and Wales", "England, Scotland, Wales and the Isle of Man", "Great Britain, Ireland, Wales and Cornwall"],
    correctIndex: 0,
    explanation: "The United Kingdom is made up of England, Scotland, Wales and Northern Ireland.",
  },
  {
    id: "uk-2",
    category: "What is the UK?",
    question: "What is the capital city of Scotland?",
    options: ["Edinburgh", "Glasgow", "Aberdeen", "Dundee"],
    correctIndex: 0,
    explanation: "Edinburgh is the capital city of Scotland, home to the Scottish Parliament.",
  },
  {
    id: "uk-3",
    category: "What is the UK?",
    question: "What is the capital city of Wales?",
    options: ["Cardiff", "Swansea", "Newport", "Bangor"],
    correctIndex: 0,
    explanation: "Cardiff is the capital city of Wales and the seat of the Welsh Parliament (Senedd).",
  },
  {
    id: "uk-4",
    category: "What is the UK?",
    question: "Which of these is NOT part of the United Kingdom?",
    options: ["The Republic of Ireland", "Northern Ireland", "Wales", "Scotland"],
    correctIndex: 0,
    explanation: "The Republic of Ireland is an independent country and is not part of the UK; Northern Ireland is.",
  },
  {
    id: "uk-5",
    category: "What is the UK?",
    question: "What is the official language most commonly used across the UK?",
    options: ["English", "French", "Latin", "Gaelic"],
    correctIndex: 0,
    explanation: "English is the main language spoken throughout the UK, alongside Welsh, Scottish Gaelic and Irish in parts of the country.",
  },
  {
    id: "uk-6",
    category: "What is the UK?",
    question: "Which sea separates Great Britain from mainland Europe?",
    options: ["The English Channel", "The Irish Sea", "The North Atlantic", "The Baltic Sea"],
    correctIndex: 0,
    explanation: "The English Channel separates southern England from northern France.",
  },
  {
    id: "uk-7",
    category: "What is the UK?",
    question: "What is the currency used in the UK?",
    options: ["Pound sterling", "Euro", "US Dollar", "Punt"],
    correctIndex: 0,
    explanation: "The pound sterling (£) is the official currency of the United Kingdom.",
  },
  {
    id: "uk-8",
    category: "What is the UK?",
    question: "Which city is the capital of the United Kingdom?",
    options: ["London", "Manchester", "Birmingham", "Liverpool"],
    correctIndex: 0,
    explanation: "London is the capital city of the UK and the seat of the UK Parliament.",
  },

  // ---- British History ----
  {
    id: "hist-1",
    category: "British History",
    question: "Who was the first Roman emperor to successfully invade Britain in AD 43?",
    options: ["Claudius", "Julius Caesar", "Nero", "Hadrian"],
    correctIndex: 0,
    explanation: "Emperor Claudius led the successful Roman invasion of Britain in AD 43, beginning nearly 400 years of Roman rule.",
  },
  {
    id: "hist-2",
    category: "British History",
    question: "What event took place in 1066 that changed the course of English history?",
    options: ["The Norman Conquest", "The signing of Magna Carta", "The Black Death", "The Act of Union"],
    correctIndex: 0,
    explanation: "In 1066, William of Normandy defeated King Harold at the Battle of Hastings, becoming King William I.",
  },
  {
    id: "hist-3",
    category: "British History",
    question: "Which king had six wives during the Tudor period?",
    options: ["Henry VIII", "Henry VII", "Edward VI", "James I"],
    correctIndex: 0,
    explanation: "Henry VIII is famous for having six wives and for breaking from the Roman Catholic Church to found the Church of England.",
  },
  {
    id: "hist-4",
    category: "British History",
    question: "Who was the reigning monarch during the defeat of the Spanish Armada in 1588?",
    options: ["Elizabeth I", "Mary I", "Henry VIII", "James I"],
    correctIndex: 0,
    explanation: "Elizabeth I was queen when the English navy defeated the Spanish Armada in 1588.",
  },
  {
    id: "hist-5",
    category: "British History",
    question: "What was the name of the civil war fought in England in the 17th century between Parliament and the King?",
    options: ["The English Civil War", "The War of the Roses", "The Hundred Years' War", "The Jacobite Rising"],
    correctIndex: 0,
    explanation: "The English Civil War (1642-1651) was fought between supporters of King Charles I and Parliament.",
  },
  {
    id: "hist-6",
    category: "British History",
    question: "Which document, agreed in 1689, limited the power of the monarch and strengthened Parliament?",
    options: ["The Bill of Rights", "Magna Carta", "The Treaty of Union", "The Reform Act"],
    correctIndex: 0,
    explanation: "The Bill of Rights of 1689 established that the monarch could not raise taxes or laws without Parliament's consent.",
  },
  {
    id: "hist-7",
    category: "British History",
    question: "In which year did the Act of Union join the Kingdoms of England and Scotland?",
    options: ["1707", "1801", "1603", "1922"],
    correctIndex: 0,
    explanation: "The Act of Union in 1707 united the Parliaments of England and Scotland to create the Kingdom of Great Britain.",
  },
  {
    id: "hist-8",
    category: "British History",
    question: "Who was the British Prime Minister for most of the Second World War?",
    options: ["Winston Churchill", "Neville Chamberlain", "Clement Attlee", "Anthony Eden"],
    correctIndex: 0,
    explanation: "Winston Churchill led the UK as Prime Minister through most of the Second World War from 1940.",
  },
  {
    id: "hist-9",
    category: "British History",
    question: "What major social reform did Clement Attlee's government introduce after the Second World War?",
    options: ["The National Health Service (NHS)", "The Poll Tax", "Universal suffrage", "The Corn Laws"],
    correctIndex: 0,
    explanation: "Attlee's post-war Labour government created the NHS in 1948, providing free healthcare at the point of use.",
  },
  {
    id: "hist-10",
    category: "British History",
    question: "Which industry-driven period, beginning in the UK in the 18th century, transformed manufacturing across the world?",
    options: ["The Industrial Revolution", "The Agricultural Reform", "The Age of Enlightenment", "The Digital Revolution"],
    correctIndex: 0,
    explanation: "The Industrial Revolution began in Britain in the late 18th century, driving major advances in manufacturing and transport.",
  },
  {
    id: "hist-11",
    category: "British History",
    question: "Who is credited with the introduction of the National Health Service (NHS) in 1948?",
    options: ["Aneurin Bevan", "Florence Nightingale", "David Hume", "Winston Churchill"],
    correctIndex: 0,
    explanation: "In 1948, Aneurin (Nye) Bevan, the Minister for Health, led the establishment of the NHS, which guaranteed a minimum standard of health care for all, free at the point of use.",
  },
  {
    id: "hist-12",
    category: "British History",
    question: "Which war lasted from 1914 to 1918 and involved Britain and its empire?",
    options: ["The First World War", "The Boer War", "The Crimean War", "The Napoleonic Wars"],
    correctIndex: 0,
    explanation: "The First World War (1914-1918) involved Britain and much of its empire against Germany and its allies.",
  },

  // ---- Modern, Thriving Society ----
  {
    id: "mod-1",
    category: "Modern, Thriving Society",
    question: "Which of these is a patron saint's day celebrated in England?",
    options: ["St George's Day", "St Andrew's Day", "St David's Day", "St Patrick's Day"],
    correctIndex: 0,
    explanation: "St George's Day, on 23 April, is the patron saint's day of England.",
  },
  {
    id: "mod-2",
    category: "Modern, Thriving Society",
    question: "What is celebrated on 5 November in the UK?",
    options: ["Bonfire Night, marking the Gunpowder Plot", "The Queen's Birthday", "Remembrance Day", "May Day"],
    correctIndex: 0,
    explanation: "Bonfire Night commemorates the failed Gunpowder Plot of 1605 to blow up Parliament.",
  },
  {
    id: "mod-3",
    category: "Modern, Thriving Society",
    question: "Which famous horse race takes place at Aintree each year?",
    options: ["The Grand National", "The Derby", "Royal Ascot", "The St Leger"],
    correctIndex: 0,
    explanation: "The Grand National is a well-known steeplechase horse race held annually at Aintree, near Liverpool.",
  },
  {
    id: "mod-4",
    category: "Modern, Thriving Society",
    question: "Which UK broadcaster is funded by a licence fee and provides an impartial public service?",
    options: ["The BBC", "ITV", "Sky News", "Channel 5"],
    correctIndex: 0,
    explanation: "The BBC is funded by the licence fee and has a duty to be impartial and independent.",
  },
  {
    id: "mod-5",
    category: "Modern, Thriving Society",
    question: "What is the name of the annual arts festival held in Edinburgh each August?",
    options: ["The Edinburgh Festival Fringe", "The Notting Hill Carnival", "Glastonbury", "The Proms"],
    correctIndex: 0,
    explanation: "The Edinburgh Festival Fringe is one of the largest arts festivals in the world, held every August.",
  },
  {
    id: "mod-6",
    category: "Modern, Thriving Society",
    question: "Which sport is most associated with Wimbledon in the UK?",
    options: ["Tennis", "Football", "Cricket", "Rugby"],
    correctIndex: 0,
    explanation: "Wimbledon hosts the oldest tennis tournament in the world, first played in 1877.",
  },
  {
    id: "mod-7",
    category: "Modern, Thriving Society",
    question: "What is a 'listed building' in the UK?",
    options: ["A building protected because of its historic or architectural importance", "A building that is for sale", "A building owned by the government", "A newly constructed building"],
    correctIndex: 0,
    explanation: "Listed buildings are protected by law because of their special architectural or historic interest.",
  },
  {
    id: "mod-8",
    category: "Modern, Thriving Society",
    question: "Which of these is a well-known British newspaper?",
    options: ["The Times", "The New York Times", "Le Monde", "Der Spiegel"],
    correctIndex: 0,
    explanation: "The Times is one of the UK's long-established national newspapers, first published in 1785.",
  },
  {
    id: "mod-9",
    category: "Modern, Thriving Society",
    question: "What does the Church of England's role as the 'established church' mean?",
    options: ["It is the official state church of England, though other faiths are respected", "It is the only religion permitted in the UK", "All citizens must attend its services", "It controls the UK Parliament"],
    correctIndex: 0,
    explanation: "The Church of England is the officially established church, but the UK is a multi-faith society where other religions are respected and practised freely.",
  },
  {
    id: "mod-10",
    category: "Modern, Thriving Society",
    question: "Which of these is a well-known charity in the UK dedicated to protecting historic buildings and countryside?",
    options: ["The National Trust", "Oxfam", "The Red Cross", "Comic Relief"],
    correctIndex: 0,
    explanation: "The National Trust is a charity that protects historic places and green spaces across England, Wales and Northern Ireland.",
  },

  // ---- Government, Law and Your Role ----
  {
    id: "gov-1",
    category: "Government, Law and Your Role",
    question: "How often are general elections normally held in the UK?",
    options: ["At least every 5 years", "Every year", "Every 2 years", "Every 10 years"],
    correctIndex: 0,
    explanation: "By law, a general election must be held at least every five years, though one can be called earlier.",
  },
  {
    id: "gov-2",
    category: "Government, Law and Your Role",
    question: "What is the minimum voting age in UK general elections?",
    options: ["18", "16", "21", "25"],
    correctIndex: 0,
    explanation: "To vote in a UK general election, a person must be at least 18 years old and a British, Irish, or qualifying Commonwealth citizen.",
  },
  {
    id: "gov-3",
    category: "Government, Law and Your Role",
    question: "What is the House of Commons?",
    options: ["The elected chamber of the UK Parliament", "The unelected upper chamber of Parliament", "The monarch's private council", "A local town council"],
    correctIndex: 0,
    explanation: "The House of Commons is made up of Members of Parliament (MPs) elected by the public.",
  },
  {
    id: "gov-4",
    category: "Government, Law and Your Role",
    question: "Who is currently the Head of State of the United Kingdom?",
    options: ["The reigning monarch", "The Prime Minister", "The Speaker of the House", "The Lord Chancellor"],
    correctIndex: 0,
    explanation: "The UK is a constitutional monarchy; the reigning monarch is the Head of State, while the Prime Minister is the head of government.",
  },
  {
    id: "gov-5",
    category: "Government, Law and Your Role",
    question: "What is the role of a jury in a criminal trial?",
    options: ["To decide whether the defendant is guilty or not guilty, based on the evidence", "To act as the judge and set the sentence", "To represent the defendant in court", "To prosecute the case"],
    correctIndex: 0,
    explanation: "A jury of twelve members of the public listens to the evidence and decides on a verdict of guilty or not guilty.",
  },
  {
    id: "gov-6",
    category: "Government, Law and Your Role",
    question: "At what age can a person normally serve on a jury in England and Wales?",
    options: ["18 to 75", "16 to 65", "21 to 70", "25 to 80"],
    correctIndex: 0,
    explanation: "In England and Wales, most citizens aged 18 to 75 can be called for jury service.",
  },
  {
    id: "gov-7",
    category: "Government, Law and Your Role",
    question: "Which of these is a devolved administration within the UK?",
    options: ["The Scottish Parliament", "The House of Lords", "The Cabinet Office", "The Privy Council"],
    correctIndex: 0,
    explanation: "Scotland, Wales and Northern Ireland each have devolved administrations with powers over certain policy areas.",
  },
  {
    id: "gov-8",
    category: "Government, Law and Your Role",
    question: "What is the main function of a Member of Parliament (MP)?",
    options: ["To represent their constituency in the House of Commons", "To judge criminal cases", "To lead the local police force", "To manage a local hospital"],
    correctIndex: 0,
    explanation: "MPs are elected to represent the people of their constituency and to debate and vote on laws in the House of Commons.",
  },
  {
    id: "gov-9",
    category: "Government, Law and Your Role",
    question: "In the UK, what is 'council tax' used to pay for?",
    options: ["Local services such as rubbish collection and libraries", "National defence", "The NHS budget in full", "Members of Parliament's salaries"],
    correctIndex: 0,
    explanation: "Council tax is a local tax that helps pay for local services provided by the local authority, such as waste collection, libraries and policing.",
  },
  {
    id: "gov-10",
    category: "Government, Law and Your Role",
    question: "What should you do if you are the victim of a crime in the UK?",
    options: ["Report it to the police", "Deal with it yourself without involving anyone", "Only tell family members", "Post about it on social media instead"],
    correctIndex: 0,
    explanation: "Any crime should be reported to the police, who can be contacted on 101 for non-emergencies or 999 in an emergency.",
  },
  {
    id: "gov-11",
    category: "Government, Law and Your Role",
    question: "What is the purpose of the Human Rights Act 1998?",
    options: ["It incorporates the European Convention on Human Rights into UK law", "It sets the national minimum wage", "It establishes the NHS", "It regulates immigration"],
    correctIndex: 0,
    explanation: "The Human Rights Act 1998 gives further effect in UK law to the rights set out in the European Convention on Human Rights.",
  },
  {
    id: "gov-12",
    category: "Government, Law and Your Role",
    question: "Which emergency number should you call for the police, fire or ambulance service in a genuine emergency?",
    options: ["999", "111", "101", "112 only"],
    correctIndex: 0,
    explanation: "999 is the main emergency number in the UK for police, fire and ambulance services (112 also works, as it connects to the same service).",
  },
];
